ML-TANGO/TANGO

labelling/Server/src/routes/tangoStatus.js

start / stop rest bugfix (text plain)

---

docker-compose.yml

Add environment variable NVIDIA_VISIBLE_DEVICES

Update docker-compose.yaml for NVIDIA GPU

---

labelling/Dockerfile

dataset Import Error Fix
add   pip install

coco dataset Import Error Fix

---

README.md
autonn/neck_nas/neckNAS/etri/head.py
autonn/neck_nas/neckNAS/etri/main.py
autonn/neck_nas/neckNAS/etri/yaml/args.yaml
autonn/neck_nas/neckNAS/etri/yolov5_utils/__init__.py
autonn/neck_nas/neckNAS/etri/yolov5_utils/autoanchor.py
autonn/neck_nas/neckNAS/etri/yolov5_utils/general.py
autonn/neck_nas/neckNAS/etri/yolov5_utils/loss.py
autonn/neck_nas/neckNAS/etri/yolov5_utils/plots.py
autonn/neck_nas/neckNAS/etri/yolov5_utils/torch_utils.py
autonn/neck_nas/neckNAS/views.py

1. Fix errors importing python modules
2. Add arg.yaml and head.py

Etri autonn nk

---

labelling/Model/Dataset/DatasetImporter.py
labelling/Server/src/routes/DataSetController.js

Fixed code that was behaving incorrectly when uploading more than 1000 coco type images.

Weda labeling

---

docker-compose.yml
project_manager/frontend/src/api/api.project.js
project_manager/frontend/src/api/api.target.js
project_manager/frontend/src/api/refreshToken.js
project_manager/frontend/src/modules/common/card/TargetCard.vue
project_manager/frontend/src/modules/project/ProjectCreateDialog.vue
project_manager/frontend/src/modules/project/components/ProgressCanvas.vue
project_manager/frontend/src/modules/project/components/progress-icon/ProgressIcon.vue
project_manager/frontend/src/modules/project/tabs/ConfigurationTab.vue
project_manager/frontend/src/modules/project/tabs/ProgressTab.vue
project_manager/frontend/src/modules/target/stepper/SecondStepper.vue
project_manager/frontend/src/modules/target/stepper/ThirdStepper.vue
project_manager/frontend/src/pages/ProjectDashboard.vue
project_manager/frontend/src/pages/ProjectDetail.vue
project_manager/frontend/src/shared/enums/enums.common.js
project_manager/tango/models.py
project_manager/tango/projectHandler.py
project_manager/tango/urls.py
project_manager/tango/viewsProject.py

1. Classification Workflow 추가
2. Target info 값 변경 
변경전 :
ondevice/cloud/k8s/PCServer
변경후:
Cloud/K8S/K8S_Jetson_Nano/PC_Server/PC/Jetson_AGX_Orin/Jetson_AGX_Xavier/Jetson_Nano/Galaxy_S22/Odroid_N2

feat: Classification Workflow

---

autonn/YoloE/yoloe_core/views.py
autonn/YoloE/yoloe_core/yolov7_utils/train.py
autonn/YoloE/yoloe_core/yolov7_utils/train_aux.py
autonn/YoloE/yoloe_core/yolov7_utils/utils/datasets.py

Etri sis bms

---

docker-compose.yml
project_manager/frontend/src/shared/enums/enums.common.js
project_manager/tango/projectHandler.py

Fix: Resolve error due to Docker hostname containing underscore
변경 내용:
- 언더스코어 없이 호스트 이름을 설정하도록 변경
관련 이슈 : https://github.com/ML-TANGO/TANGO/issues/79

Teslasystem vue

---

project_manager/tango/projectHandler.py

issue :https://github.com/ML-TANGO/TANGO/issues/83

fix: depoly docker port

---

docker-compose.yml

postgres의 업데이트로 인한 오류로 15.4 버전으로 빌드되도록 수정

hotfix, Change postgres version

---

base_model_select/basemodel_yaml/resnet/resnet101.json
base_model_select/basemodel_yaml/resnet/resnet152.json
base_model_select/basemodel_yaml/resnet/resnet34.json
base_model_select/basemodel_yaml/resnet/resnet50.json

홍익대에서 작성한 resnet의 basemodel json 파일들을 BMS에 포함시켰습니다.

BMS:resnet json files for defining basemodel

---

deploy_codegen/optimize_codegen/code_gen.py

modify code_gen.py to support pt_file_name in deployment.yaml for k8s

modify code_gen.py to support pt_file_name in deployment.yaml for k8s

---

deploy_targets/k8s/Dockerfile_template
deploy_targets/k8s/deployment.py

배포 실행파일 path 변경으로  배포 시 실행파일 path 경로 수정

Change model file path

---

project_manager/tango/projectHandler.py

Modify Deploy Port
cloud_deploy: 8890
k8s_deploy: 8901
ondevice_deploy: 8891

Modify Deploy Port

---

deploy_targets/k8s/Dockerfile_new
deploy_targets/k8s/Dockerfile_template
deploy_targets/k8s/deployment.py
deploy_targets/k8s/prj-test.py

- [o] 기능 추가
- [o] 자신의 브랜치로 main 브랜치 최신 내용 반영후 동작 테스트 완료
- [o] 다른 작업자의 폴더내 파일 수정하지 않음.
- [o] docker-compose.yml 수정한 경우, 수정에 따른 영향 평가 
ex)  kpst/k8s_deploy-> main
yolov5 -> yolov7 모델 변경  및 실행 명령어 변경
정상적으로 생성 및 실행 테스트 완료

yolov7 code edit

---

autonn/YoloE/yoloe_core/views.py
autonn/YoloE/yoloe_core/yolov7_utils/export.py

ETRI_sis_YoloE_1001 -> main
YoloE에서 onnx 옵션을 결정하는 기준이 target의 engine으로 변경되었습니다.

YoloE의 onnx 옵션 결정 기준을 engine으로 변경

---

docker-compose.yml
project_manager/frontend/src/api/api.container.js
project_manager/frontend/src/api/axios.js
project_manager/frontend/src/pages/ProjectDashboard.vue
project_manager/frontend/src/pages/ProjectDetail.vue
project_manager/frontend/src/shared/enums/enums.common.js
project_manager/tango/projectHandler.py
project_manager/tango/viewsProject.py

호스트네임 변경 (컨테이너 이름과 호스트네임을 동일하게 하여 관리하는데 용이하여 변경함)
기존 : visualization 
변경 후 : viz2code
"viz2code" 컨테이너 연동 테스트 완료

Change host name for "viz2code"

---

deploy_codegen/optimize_codegen/Dockerfile
deploy_codegen/optimize_codegen/code_gen.py
deploy_codegen/optimize_codegen/db/k8soutput.py
deploy_codegen/optimize_codegen/db/tensorrt-infer-template.py

- [ o] 기능 추가
- [o] 자신의 브랜치로 main 브랜치 최신 내용 반영후 동작 테스트 완료
- [o] 다른 작업자의 폴더내 파일 수정하지 않음.
ETRI-khlee_deployment -> main
Modify tensorrt and k8s yolov7 code generation 
정상동작 확인 완료

Modify tensorrt and k8s yolov7 code generation 

---

deploy_codegen/optimize_codegen/code_gen.py
deploy_codegen/optimize_codegen/db/tensorrt-infer-template.py
deploy_codegen/optimize_codegen/db/tvm-infer-template.py

- [ o] 기능 추가
- [o ] 자신의 브랜치로 main 브랜치 최신 내용 반영후 동작 테스트 완료
- [o ] 다른 작업자의 폴더내 파일 수정하지 않음.
etri_khlee_deployment -> main
tvm and tensorrt code generation change
정상

tvm and tensorrt code generation change

---

deploy_targets/cloud/cloud_manager/service.py
deploy_targets/cloud/samples/yolov7/Dockerfile.pt
deploy_targets/cloud/samples/yolov7/Dockerfile.tensorrt
deploy_targets/cloud/samples/yolov7/README.md
deploy_targets/cloud/samples/yolov7/build_images.sh
deploy_targets/cloud/samples/yolov7/run_container.sh
deploy_targets/cloud/samples/yolov7/server/entrypoint.sh
deploy_targets/cloud/samples/yolov7/server/main.py
deploy_targets/cloud/samples/yolov7/server/requirements.txt
deploy_targets/cloud/samples/yolov7/server/static/index.html
deploy_targets/cloud/setup.cfg

`lablup-adrysn-2023-fall-demo-scenario` → `main`
- GCP 상에 배포할 YOLO v7 e6e 추론 예제 이미지 빌드
- 배포 컨테이너 생성/삭제 후 동일한 프로젝트/사용자의 배포 컨테이너가 다시 생성될 때 DB 상에서 이미 종료된 컨테이너의 상태를 업데이트 하던 문제 수정
- 정상적으로 GCP 상에 배포된 후 GCP 도메인을 통해 다음과 같은 화면이 나오고, 사용자가 자신의 이미지를 업로드 하여 object detection 결과를 볼 수 있음

misc: yolov7 e2e demo container

---

deploy_codegen/optimize_codegen/code_gen.py
deploy_codegen/optimize_codegen/db/tensorrt-infer-template.py

- [o ] 기능 추가
- [ O] 버그 수정
- [ O] 자신의 브랜치로 main 브랜치 최신 내용 반영후 동작 테스트 완료
- [ O] 다른 작업자의 폴더내 파일 수정하지 않음.
etri_khlee-deployment -> main
tensorrt 생성 모듈 수정
정상

Etri khlee deployment

---

deploy_targets/k8s/Dockerfile_new
deploy_targets/k8s/Dockerfile_template
deploy_targets/k8s/deployment.py

- [ 0 ] 기타
- [ 0 ] 자신의 브랜치로 main 브랜치 최신 내용 반영후 동작 테스트 완료
- [ 0 ] 다른 작업자의 폴더내 파일 수정하지 않음.
- [ 0 ] docker-compose.yml 수정한 경우, 수정에 따른 영향 평가 
ex) etri_kimkk_integration -> main
kpst/k8s_deploy -- main
ex) 로그인 시, 구글 소셜 로그인 기능을 추가했습니다.
컨테이너 내부포트  deployment.py 코드  8901 ->8902 수정
Dockerfile_template, deployment.py 경로 변경 수정  fileset-main -->fileset
ex) 베이스 main 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다. 결과물에 대한 스크린샷, GIF, 혹은 라이브 데모가 가능하도록 샘플API를 첨부할 수도 있습니다.

file path, internal port edit

---

autonn/YoloE/yoloe_core/yolov7_utils/train.py
autonn/YoloE/yoloe_core/yolov7_utils/train_aux.py
base_model_select/backend/views.py

- 기능 추가
- 기능 삭제
- 의존성, 환경 변수, 빌드 관련 코드 업데이트
- 기타
- docker-compose.yml 수정한 경우, 수정에 따른 영향 평가 
ETRI_sis_YoloE_1001 -> main
BMS에서 batch size를 측정할 때, 오타가 있어서 이미지 사이즈가 정확히 입력되지 않았던 버그를 수정했습니다.
(detction을 detection으로 수정)
ex) 베이스 main 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다. 결과물에 대한 스크린샷, GIF, 혹은 라이브 데모가 가능하도록 샘플API를 첨부할 수도 있습니다.

오타로 인한 버그 수정 (detection -> detection)

---

deploy_targets/cloud/cloud_manager/targets/gcp/cloudrun.py
deploy_targets/cloud/samples/yolov7/server/static/index.html

ex) lablup-adrysn-increase-memory-for-yolov7-sample -> main
GCP 상 배포하는 YOLO v7 모델의 자원 정책 변경 및 예제 프론트엔드 코드 업데이트

feat: Increase memory for YOLO v7 example

---

deploy_targets/ondevice/ondevice_deploy.py
deploy_targets/ondevice/test/ondevice_test.py

- [ o] 버그 수정
- [ o] 자신의 브랜치로 main 브랜치 최신 내용 반영후 동작 테스트 완료
- [ o] 다른 작업자의 폴더내 파일 수정하지 않음.
etri_khlee_deployment -> main
ondevice deployment error 수정
정상

ondevice deploy modify

---

project_manager/frontend/package.json
project_manager/frontend/src/api/api.container.js
project_manager/frontend/src/modules/project/components/ProgressCanvas.vue
project_manager/frontend/src/modules/project/tabs/ProgressTab.vue
project_manager/frontend/src/pages/ProjectDetail.vue
project_manager/tango/projectHandler.py
project_manager/tango/viewsProject.py

- [v] 버그 수정
- [v] 자신의 브랜치로 main 브랜치 최신 내용 반영후 동작 테스트 완료
- [v] 다른 작업자의 폴더내 파일 수정하지 않음.
- [  ] docker-compose.yml 수정한 경우, 수정에 따른 영향 평가 
teslasystem_vue -> main
- PM에서 image deploy 단계에서 download 를 여러번 수행하는 문제 해결
- status_report시 Error 발생하는 문제 해결
- download 를 여러번 수행하는 문제 해결 확인
- status_report시 Error 발생하는 문제 해결 확인

Resolve downloading multiple times in the image deployment step

---

deploy_targets/ondevice/ondevice_deploy.py

- [x ] 자신의 브랜치로 main 브랜치 최신 내용 반영후 동작 테스트 완료
- [x ] 다른 작업자의 폴더내 파일 수정하지 않음.
etri_khlee_deployment -> main
ondevice deploy threading 추가
정상

ondevie deploy add thread

---

deploy_targets/ondevice/ondevice_deploy.py

- [ x] 버그 수정
- [ x] 자신의 브랜치로 main 브랜치 최신 내용 반영후 동작 테스트 완료
- [ x] 다른 작업자의 폴더내 파일 수정하지 않음.
etri_khlee_integration -> main
ondevice threading 수정
정상

modify ondevice deploy

---

visualization/frontend/package.json

- #135 
- bugfix -> main
- delete 'react-app/jest' from eslint-config arrays in /visiualization/frontend/package.json
- success viz2code docker image build

resolved #135 delete react-app/jest from eslint-config arrays

---

base_model_select/batch_test/batch_size_test.py
base_model_select/batch_test/binary_search.py

#133 
ETRI_sis_BMS_new -> main
Batch Size 체크 시에 더 정확한 값을 탐색하도록 Binary Search 방식을 적용하였습니다.

BMS Update: The module for batch size check is improved with binary search

---

base_model_select/backend/views.py
base_model_select/batch_test/batch_size_test.py
base_model_select/batch_test/binary_search.py
base_model_select/requirements.txt

#132 
ETRI_sis_BMS_new -> main
1) BMS에서 출력되는 로그들의 포맷을 수정하였습니다. BMS에서 출력하는 로그 중 중요한 항목만 표출됩니다.
2) BMS에서 사용되었던 구버전 Django의 보안 취약점 문제를 해결하기 위해 버전을 업그레이드하였습니다.

BMS: 1) The format for the BMS log is reorganized / 2) Django version for BMS is upgraded

---

base_model_select/backend/models.py
base_model_select/backend/templates/test/detail.html
base_model_select/backend/views.py
base_model_select/base_model_select/urls.py

BMS의 DB 테이블이 변경되었습니다.
기존에 만들어진 DB 테이블이 있을 경우 에러가 발생할 수 있습니다.
다음 과정을 참고해서 기존 DB 테이블을 삭제하고 새로 생성하시기 바랍니다.
~~~
sudo docker exec -it tango-bms-1 /bin/bash        # bms container 접속
python manage.py dbshell        # DB shell 에 들어가기
DROP TABLE backend_info        # 테이블 삭제
.exit        # DB shell에서 나가기
rm backend/migrations/0001_initial.py        # 기존 마이그레이션 삭제
python manage.py migrate --fake backend zero 
python manage.py makemigrations 
python manage.py migrate --fake-initial
~~~
ETRI_sis_BMS_new -> main
BMS에서 자동으로 선택되는 모델 사이즈를 수동으로 변경할 수 있게 Web UI를 추가하였습니다.

Web UI for selecting model size manually

---

project_manager/frontend/package.json
project_manager/frontend/src/main.js
project_manager/frontend/src/modules/common/file-upload/DragAndDrop.vue
project_manager/frontend/src/modules/project/TabCard.vue
project_manager/frontend/src/modules/project/components/ProgressCanvas.vue
project_manager/frontend/src/modules/project/stepper/FirstStepper.vue
project_manager/frontend/src/modules/project/tabs/ProgressTab.vue
project_manager/frontend/src/modules/target/stepper/FirstStepper.vue
project_manager/frontend/src/modules/target/stepper/SecondStepper.vue
project_manager/frontend/src/modules/target/stepper/ThirdStepper.vue
project_manager/frontend/src/pages/CreateAccountPage.vue
project_manager/frontend/src/pages/LoginPage.vue
project_manager/frontend/src/pages/ProjectDetail.vue
project_manager/frontend/src/pages/TargetManagement.vue

vue-sweetalert2에서 발생하는 오류로
vue-sweetalert2를 sweetalert2 라이브러리로 교체하여 해결
- [V] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [V] 자신의 브랜치로 main 브랜치 최신 내용 반영후 동작 테스트 완료
- [V] 다른 작업자의 폴더내 파일 수정하지 않음.
- [V] docker-compose.yml 수정한 경우, 수정에 따른 영향 평가 
teslasysten_vue -> main
npm run build오류 해결
vue-sweetalert2에서 발생하는 오류로 
vue-sweetalert2를 sweetalert2 라이브러리로 교체하여 해결
정상적으로 빌드 완료

project manager docker build 오류 해결

---

deploy_codegen/optimize_codegen/Dockerfile

ETRI_sis_codegen -> main
codegen에서 발생하는 빌드에러를 해결하였습니다.(관련이슈: #141)
정상동작

CodeGen: Modify Dockerfile to fix build error

---

deploy_codegen/optimize_codegen/Dockerfile

#141 
#153 
ETRI_tenace_Codegen -> main
CodeGen에서 발생하는 빌드 및 런타임 에러를 고치기 위해 deploy_codegen/optimize_codegen/Dockefile을 수정하였습니다. 
1. python 3.8 기반으로 컨테이너 생성 (기존 3.6) : line 1
2. tensorflow 2.8.0으로 수정 (기존 2.4.0) : line 32
3. lauchpadlib를 openjdk 저장소 추가 전에 설치 (기존 저장소 추가 후에 설치) : line 125
**docker-compose build 성공**
**docker-compose up 성공**

Fix bug: CodeGen build & runtime error

---

project_manager/frontend/src/modules/project/ProjectCreateDialog.vue
project_manager/frontend/src/modules/project/tabs/ProgressTabV2.vue
project_manager/frontend/src/pages/ProjectDashboard.vue
project_manager/frontend/src/pages/ProjectDetail.vue
project_manager/frontend/src/shared/enums/enums.common.js
project_manager/tango/projectHandler.py
project_manager/tango/urls_other.py
project_manager/tango/viewsProject.py
project_manager/tango/viewsTarget.py

teslasystem_vue -> main
- Auto NN 8100 Port로 호출 기능 추가
- 기존 "BMS -> AutoNN -> Code Gen -> Image Deploy" 파이프라인을
"AutoNN -> Code Gen -> Image Deploy"으로 변경
- status_update API 추가  (현재는 project_manager의 Docker log를 통해서 호출 성공 여부 확인 가능)
"autonn" Container에서 status_report API를 보낼때, container_id를 autonn이 아닌 yoloe로 보내 Project_manager화면이 변경되지 않음.
그외 정상 작동 확인

status_update API 추가 및 pipeline 변경

---

autonn/autonn/autonn_core/models.py
autonn/autonn/autonn_core/serializers.py
autonn/autonn/autonn_core/tango/main/__init__.py
autonn/autonn/autonn_core/tango/main/select.py
autonn/autonn/autonn_core/tango/main/visualize.py
autonn/autonn/autonn_core/tango/viz/binder.py
autonn/autonn/autonn_core/tango/viz/graph.py
autonn/autonn/autonn_core/urls.py
autonn/autonn/autonn_core/views.py
docker-compose.yml
remove_all.sh

#157 
#162 
#169 
* Visualization 기능 통합
* Base model 시각화
* (option) 모델 편집 후 pytorch 파일 출력 (/shared/common/userid/project_id/basemodel.pth) 및 yml 파일 출력(/shared/common/userid/project_id/basemodel.yml) - 주 workflow 상에서 사용은 안 함
* 아직 Project Manager에서 AutoNN front-end를 보여주는 절차가 없기 때문에 단위 테스트 수행
* AutoNN 수행 버튼 클릭 후 베이스 모델 선택되는 로그가 보이면,
* localhost:8100으로 별도 웹 페이지 오픈
* YOLOv7-tiny, ResNet 시각화 완료
* 아직 ResNet은 AutoNN에서 ResNet 기능을 통합하기 않아서 시각화만 되고 에러 메시지 출력(추후 통합 AutoNN에서 ResNet 기능 통합 예정)
* Classification 선택 시 아직 open visualization 항목이 있음 (PM에서 수정할 것으로 예상)
* Detection 선택 시 정상 동작, 단, 갤럭시 타겟인 경우 NAS supernet에 대한 시각화는 안 됨(추후 통합 AutoNN에서 NAS 기능 통합 예정)

통합 AutoNN: Visualization 기능 통합

---

autonn/autonn/autonn_core/models.py
autonn/autonn/autonn_core/tango/common/cfg/neural_net_info.yaml
autonn/autonn/autonn_core/tango/common/models/experimental.py
autonn/autonn/autonn_core/tango/common/models/yolo.py
autonn/autonn/autonn_core/tango/main/__init__.py
autonn/autonn/autonn_core/tango/main/deploy.py
autonn/autonn/autonn_core/tango/main/export.py
autonn/autonn/autonn_core/tango/main/select.py
autonn/autonn/autonn_core/tango/main/train.py
autonn/autonn/autonn_core/tango/utils/general.py
autonn/autonn/autonn_core/tango/utils/torch_utils.py
autonn/autonn/autonn_core/views.py
autonn/autonn/visualization/public/index.html

#157
#158
* 매 epoch 마다 training loss/validation accuracy/elapsed time 을 요약하여 보내는 status_update API 추가
- update_id : epoch_summary
* CodeGen과의 원활한 연동을 위한 torchscript 모델 변환기 추가
* epoch_summary 신호 전송 확인 - PM과의 연동은 미완료
* torchscript 모델 변환 확인 - CodeGen과의 연동은 미완료

통합 AutoNN : Status Update API 추가(epoch_summary) & TorchScript 모델 변환기 추가

---

autonn/autonn/autonn_core/tango/common/cfg/args.yaml
autonn/autonn/autonn_core/tango/main/__init__.py
autonn/autonn/autonn_core/tango/main/export.py
autonn/autonn/autonn_core/tango/main/select.py
autonn/autonn/autonn_core/tango/main/train.py
autonn/autonn/autonn_core/tango/main/visualize.py
autonn/autonn/autonn_core/tango/utils/autoanchor.py
autonn/autonn/autonn_core/tango/utils/general.py
autonn/autonn/autonn_core/tango/utils/torch_utils.py
autonn/autonn/autonn_core/views.py
autonn/autonn/requirements.txt

#157
ETRI_tenace_AutoNN -> main
* target device가 가속기로 CPU를 사용할 경우, FP16 옵션(--half)을 무시하도록 수정
* status_update의 model_summary 내용 중 FLOPS 값을 str에서 float으로 변경하여 보냄
* ONNX with NMS exporter 기능 추가
* CPU로 target device 선택하면, model export할 때 half 옵션 무시(FP32로 모델 변환)
* FLOPS 값 표시 확인(정수로 표시되고 있음, 소수점 1자리까지 표시 필요/ 단위는 GFLOPS)
* ONNX END2END export 확인 - CodeGen과의 연동은 미완료

통합 AutoNN : 버그 수정 & ONNX exporter 추가

---

project_manager/datasets/views.py

teslasystem_vue -> main
데이터 셋 썸네일 생성 오류 수정
chest xray 폴더의 __MACOSX 및 .DS_Store 삭제
정상 작동 확인

fix, Fixed thumbnail creation error

---

autonn/autonn/autonn_core/tango/common/cfg/args-detection.yaml
autonn/autonn/autonn_core/tango/common/cfg/args-detection7.yaml
autonn/autonn/autonn_core/tango/main/finetune.py
autonn/autonn/autonn_core/tango/main/select.py
autonn/autonn/autonn_core/tango/main/train.py
autonn/autonn/autonn_core/tango/utils/general.py

* 현재 YOLO v.9 기반의 베이스 모델 추천이 되고 있습니다. 
- 아직 YOLO v.9 기반의 NAS 모델(yolov9-supernet)이 정의되어 있지 않습니다.
- Galaxy S22를 선택했을 때는 강제로 YOLO v.7 기반의 NAS 모델(yolov7-supernet)이 선택되도록 변경하였습니다. 
* 관련 사소한 변경 사항
- 모든 옵션을 기본적으로 YOLO v.9 모델을 학습하도록 변경되어 있습니다.  
- Galaxy S22를 선택했을 때는 YOLO v.7 옵션을 선택하도록 추가적으로 args-detection7.yaml을 생성하였습니다. 
- 마찬가지로 모든 metric / loss 함수도 YOLO v.9 모델을 위한 것이지만, Galaxy S22를 선택했을 때는 YOLO v.7 모델을 위한 metric / loss 함수를 선택하도록 hard-coding 하였습니다. 
**- 이에 대한 것은 추후 모두 삭제할 예정입니다.**  
* Galaxy S22를 선택하면 무조건 YOLOv7-Supernet이 베이스모델 선택
* NAS 동작 확인 완료

통합 AutoNN : NAS 동작을 위한 임시 수정

---

deploy_targets/cloud/README.md
deploy_targets/cloud/cloud_manager/requirements.txt
deploy_targets/cloud/cloud_manager/service.py
deploy_targets/cloud/cloud_manager/targets/aws/ecs.py
deploy_targets/cloud/cloud_manager/targets/defs.py
deploy_targets/cloud/docker-compose.yml
deploy_targets/cloud/samples/deployment_aws_ecs.yaml
deploy_targets/cloud/samples/yolov7/server/static/index.html

lablup-adrysn-aws-ecs-deploy -> main
- Added AWS ECS as a cloud deployment target with relevant configuration and service management logic.
- Updated `README.md` to include instructions for deploying to AWS ECS.
- Modified cloud manager's requirements to include boto3 for AWS interaction.
- Created sample deployment YAML for AWS ECS, showing example resource and network configurations (`samples/deployment_aws_ecs.yaml`).
Deploy log for AWS ECS:

Cloud deploy to AWS ECS

---

autonn/autonn/autonn_core/tangochat/browser.py
docker-compose.yml

etri_tenace_autonn -> main
docker compose : ollama serve port 11434 expose 삭제
TangoChat: exit process 변경: 기존 Complete 버튼 클릭 -> 유저 메시지로 Bye 입력하면 종료
정상 동작 확인

Bug fix: TangoChat - port expose & exit process

---

autonn/autonn/autonn_core/tango/common/models/supernet_yolov7.py
autonn/autonn/autonn_core/tango/common/models/yolo.py
autonn/autonn/autonn_core/tango/main/select.py
autonn/autonn/autonn_core/tangochat/browser.py

etri_tenace_autonn -> main
TangoChat에서 다운로드한 LLM 모델을 삭제할 수 있는 기능을 추가하였습니다. 
TangoChat에서 다운로드 가능 모델 중 한국어 모델을 1개 추가하였습니다. 
모델 삭제 정상 동작
한국어 모델 정상 동작

Add DELETE tab in TangoChat

---

.gitignore
autonn/autonn/Dockerfile
autonn/autonn/autonn_core/tangochat/browser.py
autonn/autonn/autonn_core/tangochat/tuner/rag.py

etri_tenace_autonn -> main
TangoChat: LangChain을 활용하여 간단한 RAG를 테스트해 볼 수 있는 기능을 추가하였습니다.
LangChain에서 사용하는 DB인 Chroma 덕분에 생기는 .chroma 디렉토리를 .gitignore에 추가하였습니다.  
RAG 기능 동작 확인

Add simple RAG feature in TangoChat

---

deploy_targets/cloud/cloud_manager/targets/abc.py
deploy_targets/cloud/cloud_manager/targets/aws/ecs.py
deploy_targets/cloud/cloud_manager/targets/gcp/cloudrun.py

support AWS ECS & GCP for deploy container
- [V] 기능 추가
etri_kimkk_integration -> main
AWS ECS, GCP의 start_service, stop_service, get_service_status 구현 
ex) 베이스 main 브랜치에 포함되기 위한 코드는 모두 정상적으로 동작해야 합니다. 결과물에 대한 스크린샷, GIF, 혹은 라이브 데모가 가능하도록 샘플API를 첨부할 수도 있습니다.

support AWS ECS & GCP for deploy container

---

deploy_targets/cloud/cloud_manager/server.py
deploy_targets/cloud/cloud_manager/service.py
deploy_targets/cloud/cloud_manager/targets/abc.py
deploy_targets/cloud/cloud_manager/targets/aws/ecs.py
deploy_targets/cloud/cloud_manager/targets/gcp/cloudrun.py

- [V] 기능 추가
- [V] 버그 수정
- [V] 의존성, 환경 변수, 빌드 관련 코드 업데이트
- [V] 자신의 브랜치로 main 브랜치 최신 내용 반영후 동작 테스트 완료
lablup-dhsung-ecs-gcp-deploy-> main
AWS ECS 및 GCP CloudRun 에서 실행 관련 이슈 수정 및 
실행관련 옵션 추가, 하드코딩된 부분 리펙토링함 
AWS ECS 및 GCP CloudRun에서 yolov9 정상 실행 확인

modify features for AWS ECS and GCP CloudRun

---

deploy_targets/cloud/cloud_manager/targets/defs.py
deploy_targets/cloud/cloud_manager/targets/ktc/ktc.py

Add KT Cloud as a deploy target
- [V] 기능 추가
- [V] 자신의 브랜치로 main 브랜치 최신 내용 반영후 동작 테스트 완료
- [V] 다른 작업자의 폴더내 파일 수정하지 않음.
lablup-dhsung-ecs-gcp-deploy -> main
KT Cloud 에서 CPU/GPU할당하여 시작, 상태확인, 중지에 대한 기능 추가 
캡쳐화면
GPU연동하여 동영상 실행 화면 
yolov9실행시 GPU사용 현황도 같이 조회

Add KT Cloud as a deploy target

---

autonn/autonn/autonn_core/tango/main/select.py

…b UI
ETRI-tenace-AutoNN-> main
프로젝트 관리자에서 편집한 하이퍼파라메터와 옵션 YAML 파일을 읽어오도록 변경
편집된 YAML 파일에 따라 동작하는 것을 확인

웹UI에서 편집된 YAML 읽어오도록 변경

---

autonn/autonn/autonn_core/models.py
autonn/autonn/autonn_core/serializers.py
autonn/autonn/autonn_core/urls.py
autonn/autonn/autonn_core/views.py

Description:
- This PR includes a full cleanup and refactor of the following modules:  
* models.py
* serializers.py
* urls.py
* views.py
Changes made:
* Applied PEP8 formatting and consistent import ordering
* Removed unused or commented-out legacy code
* Improved exception handling and dictionary access safety
* Added missing docstrings for API views and utility functions
* Standardized response formats and status codes
- Verified that AutoNN and all related containers behave exactly the same as before.
- No regression or unexpected behavior observed.

Refactor API modules and verify container behavior consistency

---

autonn/autonn/autonn_core/tango/main/select.py

없음
AutoNN Core 모듈의 entry point인 select.py 전반에 걸쳐 PEP8 스타일 가이드에 맞게 리팩토링
* 코드 스타일 정리(들여쓰기, 줄 길이, 공백 등)
* 불필요한 주석 및 정리되지 않은 import 제거
* import 순서 및 블록 정리
* 코드 가독성 향상을 위한 일부 코드의 함수화, 개행 및 문서 주석 정리
* 기능 변화는 없음
* 기존 시나리오에 대해 정상 동작 확인
* 변경 전/후 기능 동일함을 확인하였고, 코드 실행 및 로그 출력 이상 없음

refactor(autonn): apply PEP8 formatting and clean up code structure

---

deploy_codegen/optimize_codegen/Dockerfile

main -> main
윈도우환경에서 도커 실행시 cython이 install 되어있지 않음
deploy_codegen/optimize_codegen의 docker file에 pip3 install cython 추가함
빌드 성공

added install of cython

---

autonn/autonn/autonn_core/tango/common/cfg/args-search.yaml
autonn/autonn/autonn_core/tango/common/cfg/neural_net_info.yaml
autonn/autonn/autonn_core/tango/common/cfg/yolov9/yolov9-supernet.yaml
autonn/autonn/autonn_core/tango/common/cfg/yolov9/yolov9-supernet.yml
autonn/autonn/autonn_core/tango/common/models/__init__.py
autonn/autonn/autonn_core/tango/common/models/supernet_yolov9.py
autonn/autonn/autonn_core/tango/common/models/yolo.py
autonn/autonn/autonn_core/tango/inference/libTango.py
autonn/autonn/autonn_core/tango/main/export.py
autonn/autonn/autonn_core/tango/main/finetune.py
autonn/autonn/autonn_core/tango/main/search.py
autonn/autonn/autonn_core/tango/main/select.py
autonn/autonn/autonn_core/tango/main/test.py
autonn/autonn/autonn_core/tango/main/train.py
autonn/autonn/autonn_core/tango/nas/predictors/accuracy_predictor/accuracy_calculator.py
autonn/autonn/autonn_core/tango/nas/search_algorithm/evolution_search.py
autonn/autonn/autonn_core/tango/utils/autobatch.py
base_model_select/backend/views.py
base_model_select/basemodel_yaml/yolov9/yolov9-c.yaml
base_model_select/basemodel_yaml/yolov9/yolov9-e.yaml
base_model_select/basemodel_yaml/yolov9/yolov9-m.yaml
base_model_select/basemodel_yaml/yolov9/yolov9-s.yaml
base_model_select/basemodel_yaml/yolov9/yolov9-t.yaml
base_model_select/basemodel_yaml/yolov9/yolov9.yaml
base_model_select/batch_test/batch_size_test.py
base_model_select/hyperparam_yaml/yolov9/hyp.scratch.p5.yaml
base_model_select/hyperparam_yaml/yolov9/hyp.scratch.p6.yaml
base_model_select/hyperparam_yaml/yolov9/hyp.scratch.tiny.yaml
base_model_select/sample_yaml/project_info.yaml

- base_model_select 변경
- backend
- views.py
- yolov9으로 변경
- basemodel_yaml
- yolov9 폴더 및 yaml 파일 생성
- batch_test
- batch_size_test.py
- yolov9으로 변경
- hyperparam_yaml
- yolov9 폴더 및 yaml 파일 생성
- samle_yaml
- project_info.yaml
- nas_type → yolov9 변경
ex) cau_autonn_yolov9nasv2 -> main
1. YOLOv9-NAS 변경 및 추가
- autonn/autonn
- Dockerfile 수정
- autonn/autonn/autonn_core/tango
- common/cfg/yolov9
- yolov9-supernet.yml 생성
- yolov9-supernet.yaml 생성
- common/cfg
- args-search.yaml 수정
- neural_net_info.yaml 수정
- common/models
- __init__.py 수정
- supernet_yolov9.py 생성
- inference
- libTango.py 수정
- main
- export.py 수정
- finetune.py 수정
- select.py 수정
- train.py 수정
- search.py 수정
- test.py 수정
- nas/search_algorithm
- evolution_search.py 수정
- …

YOLOv9-NAS 변경
